In [2]:
import pandas as pd
import numpy as np
import os


train_path = "D:/Project/RailInsight/data/raw/ir_train.csv"
train = pd.read_csv(train_path)

print(train)

         journey_id  train_number            train_type departure_date  year  \
0        IR01717809         12536     Superfast Express     2023-09-18  2023
1        IR00931776         12806     Superfast Express     2020-04-09  2020
2        IR00096904         22416  Vande Bharat Express     2024-12-13  2024
3        IR00047736         12250    Garib Rath Express     2018-11-29  2018
4        IR00726037         74588             DEMU/MEMU     2020-06-18  2020
...             ...           ...                   ...            ...   ...
1499995  IR01569648         12784     Superfast Express     2020-04-02  2020
1499996  IR00761386         74780             DEMU/MEMU     2018-01-30  2018
1499997  IR01591784         74201             DEMU/MEMU     2020-05-28  2020
1499998  IR01421505         11433          Mail/Express     2021-04-08  2021
1499999  IR01088436         12454       Duronto Express     2022-12-08  2022

         month  day_of_week  departure_hour  is_weekend  is_night_departure  \
0            9            0               7           0                   0
1            4            3               8           0                   0
2           12            4              18           0                   0
3           11            3              18           0                   0
4            6            3               5           0                   0
...        ...          ...             ...         ...                 ...
1499995      4            3               1           0                   1
1499996      1            1              18           0                   0
1499997      5            3               4           0                   1
1499998      4            3               6           0                   0
1499999     12            3               6           0                   0

         ...  is_rake_shared  maintenance_score seat_utilisation_pct  \
0        ...               1                5.5                 88.8
1        ...               1                6.6                 83.6
2        ...               0                4.1                 81.6
3        ...               0                5.5                 82.1
4        ...               1                8.0                 58.3
...      ...             ...                ...                  ...
1499995  ...               0                6.7                 66.1
1499996  ...               1                6.0                 83.9
1499997  ...               0                4.2                 94.5
1499998  ...               0                5.5                 69.4
1499999  ...               1                6.8                 90.8

        is_overloaded late_incoming_rake is_special_train  \
0                   0                  0                0
1                   0                  0                0
2                   0                  0                0
3                   0                  1                0
4                   0                  1                0
...               ...                ...              ...
1499995             0                  0                0
1499996             0                  0                1
1499997             0                  0                0
1499998             0                  1                0
1499999             0                  0                0

        route_historical_ontime_pct      primary_delay_cause  delay_minutes  \
0                              67.8  Flooding / Waterlogging            110
1                              57.0                  On Time              3
2                              81.8                  On Time              5
3                              52.3         Track Congestion            135
4                              64.3         Track Congestion            154
...                             ...                      ...            ...
1499995                        71.7                  On Time              1
1499996                        42.5     Level Crossing Delay            139
1499997                        51.4     Level Crossing Delay            116
1499998                        82.1                  On Time             14
1499999                        64.4     Fog / Low Visibility            114

         is_delayed
0                 1
1                 0
2                 0
3                 1
4                 1
...             ...
1499995           0
1499996           1
1499997           1
1499998           0
1499999           1

[1500000 rows x 45 columns]

In [3]:
train.head()

,journey_id,train_number,train_type,departure_date,year,month,day_of_week,departure_hour,is_weekend,is_night_departure,...,is_rake_shared,maintenance_score,seat_utilisation_pct,is_overloaded,late_incoming_rake,is_special_train,route_historical_ontime_pct,primary_delay_cause,delay_minutes,is_delayed
0,IR01717809,12536,Superfast Express,2023-09-18,2023,9,0,7,0,0,...,1,5.5,88.8,0,0,0,67.8,Flooding / Waterlogging,110,1
1,IR00931776,12806,Superfast Express,2020-04-09,2020,4,3,8,0,0,...,1,6.6,83.6,0,0,0,57.0,On Time,3,0
2,IR00096904,22416,Vande Bharat Express,2024-12-13,2024,12,4,18,0,0,...,0,4.1,81.6,0,0,0,81.8,On Time,5,0
3,IR00047736,12250,Garib Rath Express,2018-11-29,2018,11,3,18,0,0,...,0,5.5,82.1,0,1,0,52.3,Track Congestion,135,1
4,IR00726037,74588,DEMU/MEMU,2020-06-18,2020,6,3,5,0,0,...,1,8.0,58.3,0,1,0,64.3,Track Congestion,154,1

In [4]:
train.shape

(1500000, 45)

In [5]:
train.info()

<class 'pandas.DataFrame'>
RangeIndex: 1500000 entries, 0 to 1499999
Data columns (total 45 columns):
 #   Column                        Non-Null Count    Dtype
---  ------                        --------------    -----
 0   journey_id                    1500000 non-null  str
 1   train_number                  1500000 non-null  int64
 2   train_type                    1500000 non-null  str
 3   departure_date                1500000 non-null  str
 4   year                          1500000 non-null  int64
 5   month                         1500000 non-null  int64
 6   day_of_week                   1500000 non-null  int64
 7   departure_hour                1500000 non-null  int64
 8   is_weekend                    1500000 non-null  int64
 9   is_night_departure            1500000 non-null  int64
 10  is_peak_hour                  1500000 non-null  int64
 11  is_festival_season            1500000 non-null  int64
 12  season                        1500000 non-null  str
 13  zone                          1500000 non-null  str
 14  zone_abbr                     1500000 non-null  str
 15  source_station_category       1500000 non-null  str
 16  destination_station_category  1500000 non-null  str
 17  distance_km                   1500000 non-null  int64
 18  num_scheduled_stops           1500000 non-null  int64
 19  scheduled_travel_hours        1500000 non-null  float64
 20  track_doubled                 1500000 non-null  int64
 21  is_hdn_route                  1500000 non-null  int64
 22  traction_type                 1500000 non-null  str
 23  is_electrified                1500000 non-null  int64
 24  psr_count                     1500000 non-null  int64
 25  is_circular_route             1500000 non-null  int64
 26  is_monsoon_season             1500000 non-null  int64
 27  is_fog_risk                   1500000 non-null  int64
 28  fog_risk_score                1500000 non-null  float64
 29  zone_fog_index                1500000 non-null  float64
 30  zone_congestion_index         1500000 non-null  float64
 31  season_severity_score         1500000 non-null  float64
 32  loco_age_years                1500000 non-null  float64
 33  coach_age_years               1500000 non-null  float64
 34  has_lhb_coaches               1500000 non-null  int64
 35  is_rake_shared                1500000 non-null  int64
 36  maintenance_score             1500000 non-null  float64
 37  seat_utilisation_pct          1500000 non-null  float64
 38  is_overloaded                 1500000 non-null  int64
 39  late_incoming_rake            1500000 non-null  int64
 40  is_special_train              1500000 non-null  int64
 41  route_historical_ontime_pct   1500000 non-null  float64
 42  primary_delay_cause           1500000 non-null  str
 43  delay_minutes                 1500000 non-null  int64
 44  is_delayed                    1500000 non-null  int64
dtypes: float64(10), int64(25), str(10)
memory usage: 665.2 MB

In [6]:
train.columns.tolist()

['journey_id',
 'train_number',
 'train_type',
 'departure_date',
 'year',
 'month',
 'day_of_week',
 'departure_hour',
 'is_weekend',
 'is_night_departure',
 'is_peak_hour',
 'is_festival_season',
 'season',
 'zone',
 'zone_abbr',
 'source_station_category',
 'destination_station_category',
 'distance_km',
 'num_scheduled_stops',
 'scheduled_travel_hours',
 'track_doubled',
 'is_hdn_route',
 'traction_type',
 'is_electrified',
 'psr_count',
 'is_circular_route',
 'is_monsoon_season',
 'is_fog_risk',
 'fog_risk_score',
 'zone_fog_index',
 'zone_congestion_index',
 'season_severity_score',
 'loco_age_years',
 'coach_age_years',
 'has_lhb_coaches',
 'is_rake_shared',
 'maintenance_score',
 'seat_utilisation_pct',
 'is_overloaded',
 'late_incoming_rake',
 'is_special_train',
 'route_historical_ontime_pct',
 'primary_delay_cause',
 'delay_minutes',
 'is_delayed']

# Next task: Basic Data Quality Check

1. Are values missing?
2. Are records duplicated?
3. How many journeys were delayed?
4. What percentage of journeys were delayed?

In [7]:
summary = pd.DataFrame({
    "Column": train.columns,
    "Data Type": train.dtypes.astype(str).values,
    "Non-Null Count": train.notna().sum().values,
    "Missing Count": train.isna().sum().values,
    "Missing %": (train.isna().mean() * 100).round(2).values,
    "Unique Values": train.nunique().values
})

summary

,Column,Data Type,Non-Null Count,Missing Count,Missing %,Unique Values
0,journey_id,str,1500000,0,0.0,1500000
1,train_number,int64,1500000,0,0.0,6293
2,train_type,str,1500000,0,0.0,15
3,departure_date,str,1500000,0,0.0,2556
4,year,int64,1500000,0,0.0,7
5,month,int64,1500000,0,0.0,12
6,day_of_week,int64,1500000,0,0.0,7
7,departure_hour,int64,1500000,0,0.0,24
8,is_weekend,int64,1500000,0,0.0,2
9,is_night_departure,int64,1500000,0,0.0,2
10,is_peak_hour,int64,1500000,0,0.0,2
11,is_festival_season,int64,1500000,0,0.0,2
12,season,str,1500000,0,0.0,6
13,zone,str,1500000,0,0.0,16
14,zone_abbr,str,1500000,0,0.0,16
15,source_station_category,str,1500000,0,0.0,6
16,destination_station_category,str,1500000,0,0.0,6
17,distance_km,int64,1500000,0,0.0,2868
18,num_scheduled_stops,int64,1500000,0,0.0,33
19,scheduled_travel_hours,float64,1500000,0,0.0,3683
20,track_doubled,int64,1500000,0,0.0,2
21,is_hdn_route,int64,1500000,0,0.0,2
22,traction_type,str,1500000,0,0.0,3
23,is_electrified,int64,1500000,0,0.0,2
24,psr_count,int64,1500000,0,0.0,16
25,is_circular_route,int64,1500000,0,0.0,2
26,is_monsoon_season,int64,1500000,0,0.0,2
27,is_fog_risk,int64,1500000,0,0.0,2
28,fog_risk_score,float64,1500000,0,0.0,14
29,zone_fog_index,float64,1500000,0,0.0,13
30,zone_congestion_index,float64,1500000,0,0.0,16
31,season_severity_score,float64,1500000,0,0.0,11
32,loco_age_years,float64,1500000,0,0.0,401
33,coach_age_years,float64,1500000,0,0.0,449
34,has_lhb_coaches,int64,1500000,0,0.0,2
35,is_rake_shared,int64,1500000,0,0.0,2
36,maintenance_score,float64,1500000,0,0.0,91
37,seat_utilisation_pct,float64,1500000,0,0.0,701
38,is_overloaded,int64,1500000,0,0.0,1
39,late_incoming_rake,int64,1500000,0,0.0,2
40,is_special_train,int64,1500000,0,0.0,2
41,route_historical_ontime_pct,float64,1500000,0,0.0,651
42,primary_delay_cause,str,1500000,0,0.0,15
43,delay_minutes,int64,1500000,0,0.0,466
44,is_delayed,int64,1500000,0,0.0,2

Check all journey id is unique

In [8]:
train["journey_id"].is_unique

True

Duplicate rows

In [9]:
train.duplicated().sum()

np.int64(0)

Unique journey ID

In [10]:
train["journey_id"].is_unique

True

Overloaded Values

In [11]:
train["is_overloaded"].value_counts()

is_overloaded
0    1500000
Name: count, dtype: int64

Department hour range

In [12]:
train["departure_hour"].min(), train["departure_hour"].max()

(np.int64(0), np.int64(23))

Month range

In [13]:
train["month"].min(), train["month"].max()

(np.int64(1), np.int64(12))

Day of week distribution

In [14]:
train["day_of_week"].value_counts().sort_index()

day_of_week
0    215401
1    213377
2    213706
3    214254
4    213806
5    214547
6    214909
Name: count, dtype: int64

Date range

In [15]:
train["departure_date"].min(), train["departure_date"].max()

('2018-01-01', '2024-12-30')

Traget Distribution

In [16]:
train['is_delayed'].value_counts()

is_delayed
1    1078329
0     421671
Name: count, dtype: int64

# Next step: verify the date related columns
------------------------------------------------------
Before moving into actual analysis, let's make sure:

departure_date → year → month → day_of_week

In [17]:
train["departure_date"]=pd.to_datetime(train["departure_date"])

In [18]:
train["departure_date"].dt.year.value_counts().sort_index()

departure_date
2018    213861
2019    214095
2020    214236
2021    213670
2022    214353
2023    215538
2024    214247
Name: count, dtype: int64

In [19]:
train["departure_date"].dt.month.value_counts().sort_index()

departure_date
1     127871
2     116159
3     127299
4     123179
5     127469
6     123017
7     127373
8     127614
9     122794
10    127778
11    122704
12    126743
Name: count, dtype: int64

In [20]:
train["departure_date"].dt.dayofweek.value_counts().sort_index()

departure_date
0    215401
1    213377
2    213706
3    214254
4    213806
5    214547
6    214909
Name: count, dtype: int64

# One final validation before cleaning
---

Let's check whether the existing year and month columns exactly match the date-derived values.

In [21]:
(train["year"] != train["departure_date"].dt.year).sum()

np.int64(0)

In [22]:
(train["month"] != train["departure_date"].dt.month).sum()

np.int64(0)

In [23]:
# 1. Date conversion
train['departure_date'] = pd.to_datetime(train['departure_date'])

# 2. Identifier conversion
train['train_number'] = train['train_number'].astype(str)

# 3. Categorical conversion (Memory saving)
cat_cols = ['train_type', 'season', 'zone', 'zone_abbr', 'source_station_category', 
            'destination_station_category', 'traction_type', 'primary_delay_cause']
for col in cat_cols:
    train[col] = train[col].astype('category')

In [24]:
train.dtypes

journey_id                                 str
train_number                               str
train_type                            category
departure_date                  datetime64[us]
year                                     int64
month                                    int64
day_of_week                              int64
departure_hour                           int64
is_weekend                               int64
is_night_departure                       int64
is_peak_hour                             int64
is_festival_season                       int64
season                                category
zone                                  category
zone_abbr                             category
source_station_category               category
destination_station_category          category
distance_km                              int64
num_scheduled_stops                      int64
scheduled_travel_hours                 float64
track_doubled                            int64
is_hdn_route                             int64
traction_type                         category
is_electrified                           int64
psr_count                                int64
is_circular_route                        int64
is_monsoon_season                        int64
is_fog_risk                              int64
fog_risk_score                         float64
zone_fog_index                         float64
zone_congestion_index                  float64
season_severity_score                  float64
loco_age_years                         float64
coach_age_years                        float64
has_lhb_coaches                          int64
is_rake_shared                           int64
maintenance_score                      float64
seat_utilisation_pct                   float64
is_overloaded                            int64
late_incoming_rake                       int64
is_special_train                         int64
route_historical_ontime_pct            float64
primary_delay_cause                   category
delay_minutes                            int64
is_delayed                               int64
dtype: object

In [25]:
train.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 1500000 entries, 0 to 1499999
Data columns (total 45 columns):
 #   Column                        Non-Null Count    Dtype
---  ------                        --------------    -----
 0   journey_id                    1500000 non-null  str
 1   train_number                  1500000 non-null  str
 2   train_type                    1500000 non-null  category
 3   departure_date                1500000 non-null  datetime64[us]
 4   year                          1500000 non-null  int64
 5   month                         1500000 non-null  int64
 6   day_of_week                   1500000 non-null  int64
 7   departure_hour                1500000 non-null  int64
 8   is_weekend                    1500000 non-null  int64
 9   is_night_departure            1500000 non-null  int64
 10  is_peak_hour                  1500000 non-null  int64
 11  is_festival_season            1500000 non-null  int64
 12  season                        1500000 non-null  category
 13  zone                          1500000 non-null  category
 14  zone_abbr                     1500000 non-null  category
 15  source_station_category       1500000 non-null  category
 16  destination_station_category  1500000 non-null  category
 17  distance_km                   1500000 non-null  int64
 18  num_scheduled_stops           1500000 non-null  int64
 19  scheduled_travel_hours        1500000 non-null  float64
 20  track_doubled                 1500000 non-null  int64
 21  is_hdn_route                  1500000 non-null  int64
 22  traction_type                 1500000 non-null  category
 23  is_electrified                1500000 non-null  int64
 24  psr_count                     1500000 non-null  int64
 25  is_circular_route             1500000 non-null  int64
 26  is_monsoon_season             1500000 non-null  int64
 27  is_fog_risk                   1500000 non-null  int64
 28  fog_risk_score                1500000 non-null  float64
 29  zone_fog_index                1500000 non-null  float64
 30  zone_congestion_index         1500000 non-null  float64
 31  season_severity_score         1500000 non-null  float64
 32  loco_age_years                1500000 non-null  float64
 33  coach_age_years               1500000 non-null  float64
 34  has_lhb_coaches               1500000 non-null  int64
 35  is_rake_shared                1500000 non-null  int64
 36  maintenance_score             1500000 non-null  float64
 37  seat_utilisation_pct          1500000 non-null  float64
 38  is_overloaded                 1500000 non-null  int64
 39  late_incoming_rake            1500000 non-null  int64
 40  is_special_train              1500000 non-null  int64
 41  route_historical_ontime_pct   1500000 non-null  float64
 42  primary_delay_cause           1500000 non-null  category
 43  delay_minutes                 1500000 non-null  int64
 44  is_delayed                    1500000 non-null  int64
dtypes: category(8), datetime64[us](1), float64(10), int64(24), str(2)
memory usage: 456.3 MB

In [26]:
(train["year"] != train["departure_date"].dt.year).sum()
(train["month"] != train["departure_date"].dt.month).sum()

np.int64(0)

## Data Quality & Validation — Conclusion

The RailInsight dataset contains 1,500,000 rows and 45 columns.

Data quality checks performed:

- No missing values were found.
- No completely duplicated rows were found.
- journey_id is unique for every journey.
- Month values are within the valid range of 1–12.
- Departure hour values are within the valid range of 0–23.
- day_of_week values are within the valid range of 0–6.
- departure_date was converted from string to datetime.
- year and month columns were validated against departure_date.
- No mismatches were found between derived and existing date fields.
- train_number was converted to string because it is an identifier.
- Repeated categorical columns were converted to category dtype.
- is_overloaded contains only the value 0 and therefore has no variation.

Overall, the dataset passed the major data quality and consistency checks and is ready for Exploratory Data Analysis (EDA).

from pathlib import Path

processed_dir = Path("../data/processed")
processed_dir.mkdir(parents=True, exist_ok=True)

In [27]:
from pathlib import Path

processed_dir = Path("../data/processed")
processed_dir.mkdir(parents=True, exist_ok=True)

In [28]:
train.to_parquet(
    "../data/processed/train_cleaned.parquet",
    index=False
)

In [29]:
from pathlib import Path

Path("../data/processed/train_cleaned.parquet").exists()

True

In [30]:
test_train = pd.read_parquet(
    "../data/processed/train_cleaned.parquet"
)

test_train.shape

(1500000, 45)

In [31]:
test_train.dtypes

journey_id                                 str
train_number                               str
train_type                            category
departure_date                  datetime64[us]
year                                     int64
month                                    int64
day_of_week                              int64
departure_hour                           int64
is_weekend                               int64
is_night_departure                       int64
is_peak_hour                             int64
is_festival_season                       int64
season                                category
zone                                  category
zone_abbr                             category
source_station_category               category
destination_station_category          category
distance_km                              int64
num_scheduled_stops                      int64
scheduled_travel_hours                 float64
track_doubled                            int64
is_hdn_route                             int64
traction_type                         category
is_electrified                           int64
psr_count                                int64
is_circular_route                        int64
is_monsoon_season                        int64
is_fog_risk                              int64
fog_risk_score                         float64
zone_fog_index                         float64
zone_congestion_index                  float64
season_severity_score                  float64
loco_age_years                         float64
coach_age_years                        float64
has_lhb_coaches                          int64
is_rake_shared                           int64
maintenance_score                      float64
seat_utilisation_pct                   float64
is_overloaded                            int64
late_incoming_rake                       int64
is_special_train                         int64
route_historical_ontime_pct            float64
primary_delay_cause                   category
delay_minutes                            int64
is_delayed                               int64
dtype: object